### ISSUE TITLE
Demo project on Windows 10

### ISSUE THREAD

**Issue by vluv99** [googlesamples/assistant-sdk-python#246]
I'm trying to run the sample project on my windows machine
After following this [tutorial](https://developers.google.com/assistant/sdk/guides/service/python/embed/run-sample) i get the following errors:

```
C:\Users\vluv\Desktop>googlesamples-assistant-pushtotalk --project-id st-project-f30ae --device-model-id st-project-f30ae-my-computer-viy72m
INFO:root:Connecting to embeddedassistant.googleapis.com
INFO:root:Using device model st-project-f30ae-my-computer-viy72m and device id c4df5240-54ef-11e8-9cca-309c238c1234
Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:Transcript of user request: "what time".
INFO:root:Transcript of user request: "what time is".
INFO:root:Transcript of user request: "what time is it".
INFO:root:Transcript of user request: "what time  is it".
INFO:root:Transcript of user request: "what time is  it".
INFO:root:Transcript of user request: "what time is it".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.
ERROR:root:Exception iterating requests!
Traceback (most recent call last):
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\googlesamples\assistant\grpc\audio_helpers.py", line 338, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\grpc\_channel.py", line 187, in consume_request_iterator
    request = next(request_iterator)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 131, in iter_log_assist_requests
    for c in self.gen_assist_requests():
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 217, in gen_assist_requests
    for data in self.conversation_stream:
RuntimeError: generator raised StopIteration
INFO:root:Transcript of user request: "what time is it".
Traceback (most recent call last):
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vluv\AppData\Local\Programs\Python\Python37\Scripts\googlesamples-assistant-pushtotalk.exe\__main__.py", line 9, in <module>
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 458, in main
    continue_conversation = assistant.assist()
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 330, in call
    start_time=start_time)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 279, in iter
    return fut.result()
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 139, in assist
    self.deadline):
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\grpc\_channel.py", line 347, in __next__
    return self._next()
  File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\grpc\_channel.py", line 330, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.CANCELLED, Cancelled)>
```

I'm quite new to this so any help is appreciated.

**Comment by GluTbl** [comment]
open File "c:\users\vluv\appdata\local\programs\python\python37\lib\site-packages\grpc\_channel.py", line 330, change comment out "raise self" to "raise StopIteration()"

**Comment by plasmalogen** [comment]
Almost same problem on Windows 7 64bit
```
ERROR:grpc._channel:Exception iterating requests!
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\audio_helpers.py", line 338, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\grpc\_channel.py", line 180, in consume_request_iterator
    request = next(request_iterator)
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 131, in iter_log_assist_requests
    for c in self.gen_assist_requests():
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 217, in gen_assist_requests
    for data in self.conversation_stream:
RuntimeError: generator raised StopIteration
INFO:root:Transcript of user request: "what time is it".
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\googlesamples-assistant-pushtotalk.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 458, in main
    continue_conversation = assistant.assist()
  File "c:\program files\python37\lib\site-packages\tenacity\__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "c:\program files\python37\lib\site-packages\tenacity\__init__.py", line 330, in call
    start_time=start_time)
  File "c:\program files\python37\lib\site-packages\tenacity\__init__.py", line 279, in iter
    return fut.result()
  File "c:\program files\python37\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\program files\python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\program files\python37\lib\site-packages\tenacity\__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 139, in assist
    self.deadline):
  File "c:\program files\python37\lib\site-packages\grpc\_channel.py", line 345, in __next__
    return self._next()
  File "c:\program files\python37\lib\site-packages\grpc\_channel.py", line 328, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"
```

**Comment by xnmb** [comment]
Same error here:

INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:Transcript of user request: "my".
INFO:root:Transcript of user request: "what".
INFO:root:Transcript of user request: "what time".
INFO:root:Transcript of user request: "what time is".
INFO:root:Transcript of user request: "what time is it".
INFO:root:Transcript of user request: "what  time is it".
INFO:root:Transcript of user request: "what time  is it".
INFO:root:Transcript of user request: "what time is  it".
INFO:root:Transcript of user request: "what time is it".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.
ERROR:grpc._channel:Exception iterating requests!
Traceback (most recent call last):
  File "C:\Program Files\Python37\Lib\site-packages\googlesamples\assistant\grpc\audio_helpers.py", line 338, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\grpc\_channel.py", line 180, in consume_request_iterator
    request = next(request_iterator)
  File "pushtotalk.py", line 131, in iter_log_assist_requests
    for c in self.gen_assist_requests():
  File "pushtotalk.py", line 217, in gen_assist_requests
    for data in self.conversation_stream:
RuntimeError: generator raised StopIteration
INFO:root:Transcript of user request: "what time is it".
Traceback (most recent call last):
  File "pushtotalk.py", line 469, in <module>
    main()
  File "C:\Program Files\Python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "pushtotalk.py", line 458, in main
    continue_conversation = assistant.assist()
  File "C:\Program Files\Python37\lib\site-packages\tenacity\__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "C:\Program Files\Python37\lib\site-packages\tenacity\__init__.py", line 330, in call
    start_time=start_time)
  File "C:\Program Files\Python37\lib\site-packages\tenacity\__init__.py", line 279, in iter
    return fut.result()
  File "C:\Program Files\Python37\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Program Files\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Program Files\Python37\lib\site-packages\tenacity\__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "pushtotalk.py", line 139, in assist
    self.deadline):
  File "C:\Program Files\Python37\lib\site-packages\grpc\_channel.py", line 345, in __next__
    return self._next()
  File "C:\Program Files\Python37\lib\site-packages\grpc\_channel.py", line 328, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"

**Comment by chaendler** [comment]
Same error on MacOS10.13

**Comment by crashangelbr** [comment]
in Windows 10 Error

`Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:Transcript of user request: "ok".
INFO:root:Transcript of user request: "ok".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.
ERROR:grpc._channel:Exception iterating requests!
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\audio_helpers.py", line 338, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\grpc\_channel.py", line 180, in consume_request_iterator
    request = next(request_iterator)
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 131, in iter_log_assist_requests
    for c in self.gen_assist_requests():
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 217, in gen_assist_requests
    for data in self.conversation_stream:
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\googlesamples-assistant-pushtotalk.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 458, in main
    continue_conversation = assistant.assist()
  File "c:\program files\python37\lib\site-packages\tenacity\__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "c:\program files\python37\lib\site-packages\tenacity\__init__.py", line 330, in call
    start_time=start_time)
  File "c:\program files\python37\lib\site-packages\tenacity\__init__.py", line 279, in iter
    return fut.result()
  File "c:\program files\python37\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\program files\python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\program files\python37\lib\site-packages\tenacity\__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 139, in assist
    self.deadline):
  File "c:\program files\python37\lib\site-packages\grpc\_channel.py", line 345, in __next__
    return self._next()
  File "c:\program files\python37\lib\site-packages\grpc\_channel.py", line 328, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"
>`

**Comment by proppy** [comment]
This should be fixed with https://github.com/googlesamples/assistant-sdk-python/commit/bd3253df3b8d55bed885c5ff9a68bc0bc23b78a8, can you give it a try?

**Comment by plasmalogen** [comment]
Thank you. It works for me.

**Comment by Nalfaria** [comment]
How do I make sure I have the latest changes included? I am still getting this Exception iterating requests error. Thanks!

**Comment by Fleker** [comment]
If you have Git setup, you should be able to do `git pull` or `git fetch origin && git reset origin/master --hard` to get the most recent changes while you are in that directory.

**Comment by proppy** [comment]
@kdoge004 you should be able to install from master with:
```
pip install "git+https://github.com/googlesamples/assistant-sdk-python.git#egg=version_subpkg&subdirectory=google-assistant-sdk"
```
Until we publish a new version of the package.

**Comment by kdoge004** [comment]
Thank you so much proppy for the quick response. I did so and I believe it installed.yet I get the same error. Any suggestions.


Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:Transcript of user request: "hello".
INFO:root:Transcript of user request: "Telugu".
INFO:root:Transcript of user request: "hello Google".
INFO:root:Transcript of user request: "hello Google".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.
ERROR:grpc._channel:Exception iterating requests!
Traceback (most recent call last):
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\googlesamples\assistant\grpc\audio_helpers.py", line 338, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\grpc\_channel.py", line 191, in consume_request_iterator
    request = next(request_iterator)
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 131, in iter_log_assist_requests
    for c in self.gen_assist_requests():
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 217, in gen_assist_requests
    for data in self.conversation_stream:
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 469, in <module>
    main()
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 458, in main
    continue_conversation = assistant.assist()
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\tenacity\__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\tenacity\__init__.py", line 330, in call
    start_time=start_time)
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\tenacity\__init__.py", line 279, in iter
    return fut.result()
  File "C:\Program Files (x86)\Python37-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Program Files (x86)\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\tenacity\__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 139, in assist
    self.deadline):
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\grpc\_channel.py", line 363, in __next__
    return self._next()
  File "C:\Users\Beans\AppData\Roaming\Python\Python37\site-packages\grpc\_channel.py", line 346, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"
>

**Comment by proppy** [comment]
Can you make sure you're installing the sdk / executing the sample with a fresh virtualenv?

```
python3 -m venv env
env/bin/python -m pip install --upgrade setuptools pip wheel
env/bin/pip install "git+https://github.com/googlesamples/assistant-sdk-python.git#egg=version_subpkg[samples]&subdirectory=google-assistant-sdk"
env/bin/googlesamples-assistant-pushtotalk
```

**Comment by kdoge004** [comment]
I'm getting a few errors like 'python3' is not recognized as an internal or external command,
operable program or batch file. If I workaround this by using py then I get the same thing with env

**Comment by proppy** [comment]
on windows I think you should be able to use `python-3.7.0.exe`.

See https://docs.python.org/3/library/venv.html.

Maybe something like:
```
c:\Python35\python -m venv c:\path\to\myenv
c:\path\to\myenv\Scripts\activate.bat
python -m pip install --upgrade setuptools pip wheel
pip install "git+https://github.com/googlesamples/assistant-sdk-python.git#egg=version_subpkg[samples]&subdirectory=google-assistant-sdk"
googlesamples-assistant-pushtotalk
```
